# Essential Julia skills

- Targets
    - Understanding values and variables
    - Defining loops, conditional expressions, and functions
    - Variable scoping rules in Julia
- Example
    - Mrode example 3.1
    - Construct a fixed effect matrix on sex

## Representing values
A *value*/Object is a representation of an entity that is stored in a computer’s memory and can be manipulated by a Julia program.

In [5]:
1

1

In [6]:
true

true

In [7]:
"Hello World"

"Hello World"

In [8]:
[1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

Type is an extremely important property of a value:

In [14]:
@show typeof(1)
@show typeof(true)
@show typeof("Hello World")
@show typeof([1, 2, 3]);

typeof(1) = Int64
typeof(true) = Bool
typeof("Hello World") = String
typeof([1, 2, 3]) = Vector{Int64}


In [15]:
# show exact memory layout of a value
@show bitstring(1)
@show bitstring(1.0)
@show bitstring(Int8(1));

bitstring(1) = "0000000000000000000000000000000000000000000000000000000000000001"
bitstring(1.0) = "0011111111110000000000000000000000000000000000000000000000000000"
bitstring(Int8(1)) = "00000001"


In [16]:
# to judge if a value is of some type, use isa
@show 1 isa Int64
@show [1, 2, 3] isa Vector{Int};

1 isa Int64 = true
[1, 2, 3] isa Vector{Int} = true


## Defining variables

A *variable* is a name that is bound to a value.

In [19]:
@show x = 1
@show y = [1, 2, 3];

x = 1 = 1
y = [1, 2, 3] = [1, 2, 3]


In [20]:
# Operator '=' only binds values to variables.
x = 1
@show x
@show typeof(x)
x = 1.0
@show x
@show typeof(x);

x = 1
typeof(x) = Int64
x = 1.0
typeof(x) = Float64


In [22]:
x = [1, 2]
y = x
@show x
y[1] = 100
@show x;

x = [1, 2]
x = [100, 2]


In [23]:
x = [1, 2]
y = copy(x)
@show x
y[1] = 100
@show x;

x = [1, 2]
x = [1, 2]


In [24]:
x = 1
y = x
@show x
y = 100
@show x;

x = 1
x = 1


In [25]:
# UTF-8 is the default encoding of Julia strings
# UTF-8 variable names are allowed
@show π
🐇 = 2023
@show 🐇
x₁ = 2
@show x₁
ε = 1e-10
@show ε;

π = π
🐇 = 2023
x₁ = 2
ε = 1.0e-10


## Control flow constructs

- Conditional evaluation
- Loops
- Compound expressions

### Conditional evaluation

`if-elseif-else-end` syntax

In [26]:
x = -7
if x > 0
    println("x is positive")
elseif x < 0
    println("x is negative")
elseif x == 0
    println("x is zero")
else
    println("x is not a number")
end;

x is negative


In [27]:
# according IEEE 754
@show NaN > 0
@show NaN < 0
@show NaN != 0
@show NaN == NaN
@show NaN >= NaN
@show NaN <= NaN
@show NaN != NaN;

NaN > 0 = false
NaN < 0 = false
NaN != 0 = true
NaN == NaN = false
NaN >= NaN = false
NaN <= NaN = false
NaN != NaN = true


In [28]:
# Be careful with floating point numbers
@show 0.1 + 0.2 == 0.3
@show 0.1 + 0.2 ≈ 0.3;

0.1 + 0.2 == 0.3 = false
0.1 + 0.2 ≈ 0.3 = true


In [29]:
# Combining several logical conditions
x = -7
@show x > 0 && x < 10
@show x < 0 || log(x) < 10  # short circuit !!!
@show -10 < x < 10;

x > 0 && x < 10 = false
x < 0 || log(x) < 10 = true
-10 < x < 10 = true


In [30]:
# Short-circuit evaluation
x > 0 && println(x)
# equivalent to
if x > 0
    println(x)
end
x > 0 || println(x)
iseven(x) && println("x is even");

-7


In [31]:
# Ternary operator
x = 1
x > 0 ? println("x is positive") : println("x is negative");

x is positive


### Loops
- `for-end` syntax
- `while-end` syntax

In [32]:
for i in [1, 2, 3]
    println(i, " is ", isodd(i) ? "odd" : "even")
end

1 is odd
2 is even
3 is odd


In [33]:
i = 1
while i < 4
    println(i, " is ", isodd(i) ? "odd" : "even")
    i += 1 # global?
end

1 is odd
2 is even
3 is odd


### Compound expressions

- `begin-end` syntax

In [34]:
x = -7
x < 0 && begin
    println(x)
    x += 1
    println(x)
    2x
end

-7
-6


-12

### Task
Construct an incidence matrix for the fixed effects (Sex) of Mrode example 3.1, where

- $\sigma_a^2 = 20$
- $\sigma_e^2 = 40$
- $\lambda = \frac{\sigma_e^2}{\sigma_a^2}$

$$y_{ij} = p_i + a_j + e_{ij}$$

Data is in file `mrode-3-1.csv`, as below:

```plaintext
# Example 3.1, pp 37, Mrode
# Linear Models for the Prediction of Animal Breeding Values
# 3ed, 2014, CABI
Calves,Sex,Sire,Dam,WWG_kg
4,Male,1,Unknown,4.5
5,Female,3,2,2.9
6,Female,1,2,3.9
7,Male,4,5,3.5
8,Male,3,6,5.0
```

In [39]:
using CSV, DataFrames

df = CSV.read("mrode-3-1.csv", 
               DataFrame, 
               header=4, 
               delim=',', 
               missingstring="Unknown")

5×5 DataFrame
 Row │ Calves  Sex      Sire   Dam      WWG_kg  
     │ Int64   String7  Int64  Int64?   Float64 
─────┼──────────────────────────────────────────
   1 │      4  Male         1  missing      4.5
   2 │      5  Female       3        2      2.9
   3 │      6  Female       1        2      3.9
   4 │      7  Male         4        5      3.5
   5 │      8  Male         3        6      5.0

I want to store all ID and their Sex in a vector of named tuples.
But I don't know how to define it.

In [41]:
typeof([(ID=1, Sex='M')])

Vector{NamedTuple{(:ID, :Sex), Tuple{Int64, Char}}} (alias for Array{NamedTuple{(:ID, :Sex), Tuple{Int64, Char}}, 1})

In [44]:
ids = Vector{NamedTuple{(:ID, :Sex), Tuple{Int64, Char}}}()

NamedTuple{(:ID, :Sex), Tuple{Int64, Char}}[]

In [45]:
for id in setdiff(df.Sire, df.Calves)
    ismissing(id) || push!(ids, (ID = id, Sex = 'M'))
end
ids

ids = NamedTuple{(:ID, :Sex), Tuple{Int64, Char}}[(ID = 1, Sex = 'M'), (ID = 3, Sex = 'M')]


2-element Vector{NamedTuple{(:ID, :Sex), Tuple{Int64, Char}}}:
 (ID = 1, Sex = 'M')
 (ID = 3, Sex = 'M')

In [46]:
for id in setdiff(df.Dam, df.Calves)
    ismissing(id) || push!(ids, (ID=id, Sex = 'F'))
end
ids

ids = NamedTuple{(:ID, :Sex), Tuple{Int64, Char}}[(ID = 1, Sex = 'M'), (ID = 3, Sex = 'M'), (ID = 2, Sex = 'F')]


3-element Vector{NamedTuple{(:ID, :Sex), Tuple{Int64, Char}}}:
 (ID = 1, Sex = 'M')
 (ID = 3, Sex = 'M')
 (ID = 2, Sex = 'F')

In [47]:
for id in eachrow(df)
    push!(ids, (ID = id.Calves, Sex = id.Sex == "Male" ? 'M' : 'F'))
end
ids

8-element Vector{NamedTuple{(:ID, :Sex), Tuple{Int64, Char}}}:
 (ID = 1, Sex = 'M')
 (ID = 3, Sex = 'M')
 (ID = 2, Sex = 'F')
 (ID = 4, Sex = 'M')
 (ID = 5, Sex = 'F')
 (ID = 6, Sex = 'F')
 (ID = 7, Sex = 'M')
 (ID = 8, Sex = 'M')

In [48]:
sort!(ids, by = x -> x.ID)

8-element Vector{NamedTuple{(:ID, :Sex), Tuple{Int64, Char}}}:
 (ID = 1, Sex = 'M')
 (ID = 2, Sex = 'F')
 (ID = 3, Sex = 'M')
 (ID = 4, Sex = 'M')
 (ID = 5, Sex = 'F')
 (ID = 6, Sex = 'F')
 (ID = 7, Sex = 'M')
 (ID = 8, Sex = 'M')

In [49]:
p = zeros(Int, length(ids), 2)
for i in 1:length(ids)
    j = ids[i].Sex == 'M' ? 1 : 2
    p[i, j] = 1
end
p

8×2 Matrix{Int64}:
 1  0
 0  1
 1  0
 1  0
 0  1
 0  1
 1  0
 1  0